version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ['nodejs']
  plugins = ['react']
  dialect = 'flow'

[[transformers]]
    name = "prettier"
    enabled = true